<?php
require __DIR__ . '/config.php';
session_start();
header('Content-Type: application/json; charset=utf-8');
function out($d){ echo json_encode(['ok'=>true,'data'=>$d]); exit; }
function fail($e,$c=400){ http_response_code($c); echo json_encode(['ok'=>false,'error'=>$e]); exit; }
function requireSuper(){ if(($_SESSION['hs_super']??false)!==true) fail('auth',401); }

$ROOT = dirname(__DIR__);                 // site root
$RESERVED = ['api','assets','css','js','img','images','fonts'];

$in = json_decode(file_get_contents('php://input'), true) ?: [];
$action = $in['action'] ?? '';

function clientDirs($ROOT,$RESERVED){
  $list=[];
  foreach(scandir($ROOT) as $d){
    if($d[0]==='.'||in_array($d,$RESERVED)||!is_dir("$ROOT/$d")) continue;
    if(!file_exists("$ROOT/$d/index.html")||!file_exists("$ROOT/$d/api/config.php")) continue;
    $cfg=file_get_contents("$ROOT/$d/api/config.php");
    $name=strtoupper($d);
    if(preg_match("/define\('COMPANY_NAME',\s*'([^']+)'\)/",$cfg,$m)) $name=$m[1];
    $installed = !preg_match('/YOUR_DB_NAME/',$cfg);
    $list[]=['code'=>$d,'name'=>$name,'configured'=>$installed];
  }
  return $list;
}
function rcopy($src,$dst){
  mkdir($dst,0755,true);
  foreach(scandir($src) as $f){
    if($f==='.'||$f==='..') continue;
    if(is_dir("$src/$f")) rcopy("$src/$f","$dst/$f");
    else copy("$src/$f","$dst/$f");
  }
}
function rdelete($dir){
  foreach(scandir($dir) as $f){
    if($f==='.'||$f==='..') continue;
    is_dir("$dir/$f") ? rdelete("$dir/$f") : unlink("$dir/$f");
  }
  rmdir($dir);
}

switch($action){

case 'login': {
  if(($in['username']??'')!==SUPER_USER || ($in['password']??'')!==SUPER_PASS) fail('invalid');
  session_regenerate_id(true);
  $_SESSION['hs_super']=true;
  out(true);
}
case 'logout': $_SESSION=[]; session_destroy(); out(true);
case 'me': (($_SESSION['hs_super']??false)===true) ? out(true) : fail('auth',401);

case 'list': { requireSuper(); out(clientDirs($ROOT,$RESERVED)); }

case 'create': {
  requireSuper();
  $code=strtolower(trim($in['code']??''));
  $name=trim($in['name']??'');
  $apass=trim($in['admin_pass']??'');
  $seed=!empty($in['seed_demo']);
  if(!preg_match('/^[a-z0-9][a-z0-9-]{1,19}$/',$code)) fail('Code must be 2–20 letters/numbers (e.g. APOLLO)');
  if(in_array($code,$RESERVED)) fail('That code is reserved — choose another');
  if(is_dir("$ROOT/$code")) fail('A client with this code already exists');
  if(!$name) fail('Company name is required');
  if(strlen($apass)<6) fail('Admin password must be at least 6 characters');
  if(!is_dir("$ROOT/".TEMPLATE_DIR)) fail('Template folder missing on server',500);
  if(strpos(DB_NAME,'YOUR_DB')!==false) fail('Fill the database details in /api/config.php first',500);

  rcopy("$ROOT/".TEMPLATE_DIR, "$ROOT/$code");

  /* rebrand every text file in the new folder */
  $CODE=strtoupper($code);
  $tplU=strtoupper(TEMPLATE_DIR); $tplN='MEDCY Hospital';
  $rii=new RecursiveIteratorIterator(new RecursiveDirectoryIterator("$ROOT/$code",FilesystemIterator::SKIP_DOTS));
  foreach($rii as $file){
    if(!in_array(strtolower($file->getExtension()),['html','php'])) continue;
    $c=file_get_contents($file->getPathname());
    $c=str_replace([$tplN,'Medcy@2026',$tplU,TEMPLATE_DIR],[$name,$apass,$CODE,$code],$c);
    file_put_contents($file->getPathname(),$c);
  }

  /* fresh tenant config with shared DB + unique prefix */
  $cfg = "<?php\n"
    ."/* Auto-generated by HamaraStaff owner panel */\n"
    ."date_default_timezone_set('Asia/Kolkata');\n"
    ."if (file_exists(__DIR__ . '/config.local.php')) require __DIR__ . '/config.local.php';\n"
    ."if (!defined('DB_HOST')) define('DB_HOST', '".addslashes(DB_HOST)."');\n"
    ."if (!defined('DB_NAME')) define('DB_NAME', '".addslashes(DB_NAME)."');\n"
    ."if (!defined('DB_USER')) define('DB_USER', '".addslashes(DB_USER)."');\n"
    ."if (!defined('DB_PASS')) define('DB_PASS', '".addslashes(DB_PASS)."');\n"
    ."define('TP', '".$code."_');\n"
    ."define('COMPANY_NAME', '".addslashes($name)."');\n"
    ."define('ADMIN_USER', 'admin');\n"
    ."define('ADMIN_PASS', '".addslashes($apass)."');\n"
    ."define('SEED_DEMO', ".($seed?'true':'false').");\n"
    ."define('RETENTION_DAYS', 365);\n"
    ."class TPDO extends PDO {\n"
    ."  #[\\ReturnTypeWillChange]\n"
    ."  public function prepare(\$sql, \$options = []) { return parent::prepare(str_replace('hs_', TP, \$sql), \$options); }\n"
    ."  #[\\ReturnTypeWillChange]\n"
    ."  public function query(\$sql, ...\$rest) { return parent::query(str_replace('hs_', TP, \$sql), ...\$rest); }\n"
    ."  #[\\ReturnTypeWillChange]\n"
    ."  public function exec(\$sql) { return parent::exec(str_replace('hs_', TP, \$sql)); }\n"
    ."}\n"
    ."function db() {\n"
    ."  static \$pdo = null;\n"
    ."  if (\$pdo) return \$pdo;\n"
    ."  \$pdo = new TPDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4', DB_USER, DB_PASS,\n"
    ."    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);\n"
    ."  return \$pdo;\n"
    ."}\n";
  file_put_contents("$ROOT/$code/api/config.php",$cfg);

  out(['code'=>$code,'url'=>'/'.$code.'/','install'=>'/'.$code.'/api/install.php']);
}

case 'remove': {
  requireSuper();
  $code=strtolower(trim($in['code']??''));
  if(!preg_match('/^[a-z0-9][a-z0-9-]{1,19}$/',$code)||in_array($code,$RESERVED)) fail('Invalid code');
  if(!is_dir("$ROOT/$code")) fail('Client not found',404);
  if(($in['confirm']??'')!==$code) fail('Confirmation text does not match the code');
  rdelete("$ROOT/$code");
  out(true);   /* note: database tables ({$code}_*) are kept for audit */
}

default: fail('unknown_action');
}
